name    'robsweet-rbenv'
version '1.2.1'
author 'robsweet'
license 'MIT'
summary 'rbenv Ruby Version Manager module'
description 'Puppet module for rbenv Ruby Version Manager'
project_page 'https://github.com/robsweet/puppet-rbenv'
